#!/bin/sh

./bin/rake spec:appraisal:cleanup spec:appraisal:install
./bin/rake spec:appraisal:rails3.0.x spec:unit
./bin/rake spec:appraisal:rails3.1.x spec:unit
./bin/rake spec:appraisal:rails3.2.x spec:unit
./bin/rake spec:appraisal:rails4.0.0rc2 spec:unit COVERAGE=true
./bin/rake spec:quality
