#!/bin/sh

./bin/rake spec:appraisal:rails3.1.x spec:unit COVERAGE=true COVERAGE_GROUP=rails31
./bin/rake spec:appraisal:rails3.2.x spec:unit
./bin/rake spec:appraisal:rails4.0.0rc2 spec:unit
./bin/rake spec:quality
